hostname RT-CORE01
!
enable secret password123
!
aaa new-model
!
aaa authentication login default local

aaa session-id common
!
username cisco privilege 15 secret password123
!
ip ssh version 2
!
interface FastEthernet0/0
 no ip address
 duplex full
!
interface Ethernet1/0
 ip address dhcp
 duplex full
!
interface Ethernet1/1
 no ip address
 shutdown
 duplex full
!
interface Ethernet1/2
 no ip address
 shutdown
 duplex full
!
interface Ethernet1/3
 no ip address
 shutdown
 duplex full
!
line con 0
 stopbits 1
line aux 0
 stopbits 1
line vty 0 4
 transport input ssh
!
end
